# Detect changes to s2n_prelude.h to update our `Package.swift` and stay in sync with it.
# See: https://github.com/awslabs/aws-crt-swift/pull/299 for updating the Package.swift.

name: s2n_prelude.h Change Detector

on: [push]

jobs:
  check-for-changes:

    runs-on: ubuntu-24.04 # latest

    steps:
    - name: Checkout Sources
      uses: actions/checkout@v4
      with:     
        submodules: true 

    - name: Check s2n_prelude.h
      run: |
        TMPFILE=$(mktemp)
          echo "116f1525acbc94c91b0ee2ea2af9fdef aws-common-runtime/s2n/utils/s2n_prelude.h" > $TMPFILE
        md5sum --check $TMPFILE

    # No further steps if successful

    - name: Echo fail
      if: failure()
      run: |
          echo "The aws-crt-swift has a hack to manually define macros which are defined in s2n_prelude.h in Package.Swift.
                This check will fail whenever s2n_prelude.h is updated by the S2N team. You should make sure that Package.Swift is updated accordingly
                with the s2n_prelude.h changes and then run `md5sum aws-common-runtime/s2n/utils/s2n_prelude.h` and update the value above."
